# Generated by Django 4.1.7 on 2023-04-01 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_shoe_date_of_manufacture'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='size',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
